### ISSUE TITLE
Issue on making internal API calls when script gets executed by queue

### ISSUE THREAD

**Issue by tizzyapunkt** [dreamfactorysoftware/df-script#3]
I do some internal api calls in a server-side node script which gets executed via the queue worker. 
The api calls fail for the production environment as it is available only via https.

The protocol is set to http here:
https://github.com/dreamfactorysoftware/df-script/blob/64136e7f0a1ce926420a220b0fbca169fc432a21/src/Engines/NodeJs.php#L64

...and the path to internal resources does not contain 'http://' or 'https://' so _protocol will be returned here:
https://github.com/dreamfactorysoftware/df-script/blob/64136e7f0a1ce926420a220b0fbca169fc432a21/src/Engines/NodeJs.php#L95

...and firing the script via queue worker does not set the protocol to 'https' here:
https://github.com/dreamfactorysoftware/df-script/blob/64136e7f0a1ce926420a220b0fbca169fc432a21/src/Engines/NodeJs.php#L65

Instead of return _protocol in the getProtocol method, i tried return 'https' which worked for me.
Thats a quick and dirty fix which works for me but there might be a better way to do that.

**Comment by leehicks** [comment]
A env configuration option will be available in the next release, see the closing commit in develop branch. Changes are also in the dreamfactory repo [here](https://github.com/dreamfactorysoftware/dreamfactory/commit/fa9fa1bb837a547adee140496295ef1d3c8f8d39).
